### ISSUE TITLE
OWA configuration options

### ISSUE THREAD

**Issue by deeztek** [vladk1m0/docker-owa#6]
I'm trying to understand how to set config options in the container, specifically e-mail server settings for password resets. According to the owa wiki, you modify the owa-config.php file. Where's this file in this container? I'm using docker-compose. Do I need to set a persistent volume to somewhere?

Thanks

**Comment by deeztek** [comment]
Bump. Anyone?

**Comment by iwismer** [comment]
Not sure if you've solved this already, but the configuration file is located at `/var/www/html/owa-config.php` after you've configured the container.
I added a volume mount for the file to my docker compose so that the configuration isn't reset:

```
owa:
    image: vladk1m0/docker-owa:latest
    container_name: owa
    depends_on:
      - owa_db
      - nginx
    networks:
      - owa_net
      - network_all
    environment:
      - TIME_ZONE="Canada/Montreal"
    volumes:
      - /mnt/data/owa/owa-config.php:/var/www/html/owa-config.php
```
